// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

func (a *Author) Books(ctx context.Context) (result []*Book, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = a.NamedBooks(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = a.Edges.BooksOrErr()
	}
	if IsNotLoaded(err) {
		result, err = a.QueryBooks().All(ctx)
	}
	return result, err
}

func (b *Book) Author(ctx context.Context) (*Author, error) {
	result, err := b.Edges.AuthorOrErr()
	if IsNotLoaded(err) {
		result, err = b.QueryAuthor().Only(ctx)
	}
	return result, MaskNotFound(err)
}
